import time
import string
if __name__ == "__main__":
    print("Load...")
    time.sleep(1)
    print("Load.......")
    time.sleep(1)
    print("Load..............")
    time.sleep(1)
    print("------------------------------------------------\n")
    print("Welcome to Python Story Generator\n")
    print("--------------------------------------------------\n")
    time.sleep(1)
    print("GAME INFO:\n")
    time.sleep(1)
    print("You have to entered to write following:\n")
    time.sleep(1)
    print("1-City\n2-Place\n3-Animal\n4-Friend Name\n5-Teacher Name")
    player_name = input("Enter your name: ")
    time.sleep(1)
    city_name= input("Enter city name: ")
    time.sleep(1)
    place_name= input("Enter place name: ")
    time.sleep(1)
    animal_name= input("Enter animal name: ")
    time.sleep(1)
    friend_name= input("Enter friend name: ")
    time.sleep(1)
    teacher_name= input("Enter teacher name: ")
    time.sleep(1)
    print("You story:\n")
    time.sleep(1)
    print(f"You have shifted to {city_name}.You are getting bore so you and your cousins decided to visit {place_name}\nYou are enjoying alot in the meantime a guide shouted that..........Harryyyy! Leave the {place_name}.A {animal_name} had attracked us.\nYou and your cnz run towards the room but suddenly {animal_name} come.You both shouder.You hit by your cnz's teacher {teacher_name}.You all run away")